---
- name: Configure and Install the Leader Node
  hosts: worker
  become: yes

  tasks:
    - name: Ensure the server is up to date
      ansible.builtin.yum:
        state: latest
        name: '*'
    - name: Install the lastest version of Cribl
      ansible.builtin.unarchive:
        src: "{{ lookup('ansible.builtin.url', 'https://cdn.cribl.io/dl/latest-arm64') }}"
        dest: /opt
        remote_src: yes
        exclude: ['._*']
    - name: Create the Cribl User
      ansible.builtin.user:
        name: cribl
        home: /opt/cribl
    - name: Set ownership of the cribl environment to the cribl user
      ansible.builtin.file:
        path: /opt/cribl
        owner: cribl
        group: cribl
        recurse: yes
        state: directory
    - name: Install the systemd service
      ansible.builtin.command:
        cmd: /opt/cribl/bin/cribl boot-start enable -u cribl
    - name: Start the Cribl Worker Node
      ansible.builtin.command:
        cmd: /opt/cribl/bin/cribl start
      environment:
        CRIBL_DIST_MASTER_URL: "{{ leader_connection }}"
      become_user: cribl
    - name: Stop the Cribl Worker Node
      ansible.builtin.command:
        cmd: /opt/cribl/bin/cribl stop
      become_user: cribl
    - name: Enable the Cribl service on reboot
      ansible.builtin.service:
        name: cribl
        state: started
        enabled: yes
...
